[package]
name = "spotify_in_russia"
version = "0.1.0"
authors = ["b3cat"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
