check_reg_exp = "(Россия|Russia|Российская Федерация|Russian Federation)"

[yes]
giphy_query = "yes"
parts = [["А Spotify наконец вышел в Росcии!"]]

[no]
giphy_query = "no"
parts = [
    ["А", "В это время", "В то время как", "Но", "В данный момент"],
    ["Spotify"],
    ["не вышел в России.", "остается недоступным.", "не вышел."],
    ["Мы продолжаем следить за ситуацией.", "Будем держать вас в курсе.", "Продолжаем наблюдение."],
]
