check_reg_exp = "(Россия|Russia|Российская Федерация|Russian Federation)"

[yes]
giphy_query = "yes"
parts = [
    ["А", "Тем временем", "Теперь", "Теперь мой дед говорит, что", "Мы едим том-ям, а"],
    ["Spotify"],
    ["наконец вышел в Росcии!", "доступен в России!", "радует российских пользователей своей доступностью!", "делает жизнь российский пользователей счастливее!"],
]

[no]
giphy_query = "no"
parts = [
    ["А", "В это время", "В то время как", "В данный момент", "Тем временем", "Как говорил мой дед:", "Кушаю чебурек, а тем временем", "Это конечно всё очень важно, но", "А Максим, у которого от 1 до 3 высших образования, сообщает, что", "Я в своем познании настолько преисполнился, а в это время", "Меня трудно найти, легко потерять и невозможно забыть, ну а", "А я люблю дождь, в нем можно спрятать свои слёзы, ведь"],
    ["Spotify"],
    ["не вышел в России.", "остается недоступным.", "не вышел.", "недоступен в России.", "вышел, но не в России.", "доступен только в мечтах российских пользователей.", "своей недоступностью заставляет грустить пользователей в России."],
    ["Мы продолжаем следить за ситуацией.", "Будем держать вас в курсе.", "Продолжаем наблюдение.", "Мы ни на секунду не прекращаем наблюдение.", "Мы, не отвлекаясь, будем следить за ситуацией.", "Ждём и следим вместе с вами.", "Сквозь слёзы продолжаем наблюдение.", "Запасаемся носовыми платками и ждем вместе с вами, друзья.", "Слезы текут, мы не сдаемся.", "Забыли обо всём на свете, просто сидим и следим за ситуацией.", "Молимся вместе с вами.", "Нельзя просто так взять и выпустить Spotify в России.", "Кофе, сигареты и мысли о нём (о Spotify).", "Keep calm and wait for Spotify."],
]
